[program:anton-poller]
command=/atlas/app/bin/anton poll
autostart=true
autorestart=true
stdout_logfile=/atlas/logs/anton-poller.log
stderr_logfile=/atlas/logs/anton-poller-error.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=1
